import * as types from './mutation-types'
const mutations={
  [types.SET_EXPAND](state,expand){
    state.expand=expand;
  },
  [types.SET_UID](state,uid){
    state.uid=uid
  },
  [types.SET_CURRENTLIST](state,currentList){
    state.currentList=currentList
  },
  [types.SET_CURRENTMUSIC](state,currentMusic){
    state.currentMusic=currentMusic
  },
  [types.SET_AUDIO](state,audio){
    state.audio=audio
  },
  [types.SET_LYRIC](state,lyric){
    state.lyric=lyric
  },
  [types.SET_PLAYING](state,playing){
    state.playing=playing
  },
  [types.SET_CURRENTINDEX](state,currentIndex){
    state.currentIndex=currentIndex
  },
  [types.SET_CURRENTLYRICINDEX](state,currentLyricIndex){
    state.currentLyricIndex=currentLyricIndex
  },
  [types.SET_MYTAB](state,myTab){
    state.myTab=myTab
  },
  [types.SET_TOPTAB](state,topTab){
    state.topTab=topTab
  },
  [types.SET_FINDTAB](state,findTab){
    state.findTab=findTab
  }
}
export default mutations